@startuml
title Component Diagram: Сервис управления пользовательскими данными

!include <C4/C4_Component.puml>

Container_Boundary(user_data_management_service, "Сервис управления пользовательскими данными")
@enduml
