@startuml
title Component Diagram: Сервис телеметрии

!include <C4/C4_Component.puml>


System_Boundary(smart_house, "Система 'Умный дом'") {
    Container("api_gateway", "API шлюз", "")

    Container_Boundary(user_data_management_service, "Сервис телеметрии") {
        Component(component_telemetry_api, "telemetry-api", "API endpoints для работы с настройками и просмотром собранных данных ", "Spring MVC")
        Component(component_telemetry, "telemetry-component", "Компонент обеспечивает функциональность для управления настройками", "Spring Bean")
        Component(component_telemetry_execution, "telemetry-request-execution-component", "Компонент обеспечивает функциональность для выполнения запросов", "Spring Bean")
    }

    Container(container_device_management, "Cервис управления устройствами", "")
    Container(container_heating_system, "Cервис управления системой отопления", "")
    Container(container_lightning_system, "Cервис управления системой освещения", "")
    Container(container_gates_system, "Cервис управления воротами", "")
    ContainerDb(db, "Собранные данных, а также данные о сохранненных настройках, статусах выполнения.", "PostgreSQL")
}

Rel(api_gateway, component_telemetry_api, "")
Rel(component_telemetry_api, component_telemetry, "")
Rel(component_telemetry, container_device_management, "")
Rel(component_telemetry, db, "")

Rel(component_telemetry_execution, container_heating_system, "")
Rel(component_telemetry_execution, container_lightning_system, "")
Rel(component_telemetry_execution, container_gates_system, "")
Rel(component_telemetry_execution, db, "")

@enduml
