@startuml
title
    Context Diagram: Система "Уьный дом"
    <i>(As-Is)</i>
end title

top to bottom direction

!include <C4/C4_Context.puml>

LAYOUT_WITH_LEGEND()

Person(user, "Пользователь", "Управляет системой отопления")
Person(technical_specialist, "Технический специалист", "Настрaивает оборудование")

System_Boundary(smart_house_boundary, "Система: Умный дом") {
    System(smart_house, "Уьный дом", "Система наблюдения и управления оборудованием в доме")
}

System_Boundary(external_house_boundary, "Дом, подключенный к системе 'Умный дом'") {
    System_Ext(heating_system, "Система управления отоплением", "API для получения и установки значений температуры")
}

Rel(user, smart_house, "Контролирует температуру", "HTTP")
Rel(technical_specialist, smart_house, "Подключает датчики и модули управления", "HTTP")
Rel(smart_house, heating_system,"Получает и устанавливает значения температуры")

@enduml
