@startuml
title
    Context Diagram: Система "Умный дом"
    <i>(To Be)</i>
end title

top to bottom direction

!include <C4/C4_Context.puml>

LAYOUT_WITH_LEGEND()

Person(user, "Пользователь")

System(smart_house, "Система 'Умный дом'", "Система управления различными системами в домах клиентов, сбора телеметрических данных и настройки сценариев работы")

System_Boundary(external_house_boundary, "Дом, подключенный к системе 'Умный дом'") {
    System_Ext(heating_system, "Система управления отоплением", "API для получения данных о текущем состоянии, а также получения и установки значений температуры")
    System_Ext(lightning_system, "Система управления освещением", "API для получения данных о текущем состоянии, а также включения и выключения освещения")
    System_Ext(gates_system, "Система управления воротами", "API для получения данных о текущем состоянии, а также открытия и закрытия ворот")
}

Rel(user, smart_house, "Использует систему (Управление устройствами, управление системами в доме, просмотр телеметрии)", "HTTP")
Rel(smart_house, heating_system,"Получает значения температуры, включает и отключает отопление", "HTTP, TCP")
Rel(smart_house, lightning_system,"Получает текущий статус световых приборов, включает и отключает освещение", "HTTP, TCP")
Rel(smart_house, gates_system,"Получает текущий статус положения ворот, открывает и закрывает ворота", "HTTP, TCP")

@enduml
