spring:
  application:
    name: device-management-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devices}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        types:
          print:
            banner: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health

monolith-api:
  url: ${MONOLITH_API_URL:http://localhost:8080/api/v1/sensors}