version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init-smarthome.sql
      - ./temperature-api/init.sql:/docker-entrypoint-initdb.d/init-temperature-api.sql
      - ./device-management-api/init.sql:/docker-entrypoint-initdb.d/init-device-management-api.sql
      - ./telemetry-api/init.sql:/docker-entrypoint-initdb.d/init-telemetry-api.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - smarthome-network

  temperature-api:
      build:
        context: ./temperature-api
        dockerfile: Dockerfile
      image: temperature-api
      container_name: temperature-api
      depends_on:
        postgres:
          condition: service_healthy
      ports:
        - "8081:8081"
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1"]
        interval: 10s
        retries: 5
        start_period: 10s
        timeout: 5s
      networks:
        - smarthome-network

  device-management-api:
    build:
      context: ./device-management-api
      dockerfile: Dockerfile
    image: device-management-api
    container_name: device-management-api
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/devices"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MONOLITH_API_URL: "http://app:8080/api/v1/sensors"
    ports:
      - "8082:8082"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    image: smarthome-app
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/smarthome"
      TEMPERATURE_API_URL: "http://temperature-api:8081"
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/health | grep ok || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - smarthome-network

volumes:
  postgres-data:

networks:
  smarthome-network:
    driver: bridge