@startuml
title Container Diagram: Система "Умный дом"

top to bottom direction

!include <C4/C4_Container.puml>

'LAYOUT_WITH_LEGEND()

Person(user, "Пользователь")

System_Boundary(smart_house, "Система 'Умный дом'") {
    Container("auth_service", "Сервис аутентификации и авторизации", "контекст: Аутентиффикация и авторизация")
    Container("api_gateway", "API шлюз", "")

    Container("user_data_management_service", "Сервис управления пользовательскими данными", "контексты: Управление пользователями, Управление домами")

    Container("device_management_service", "Сервис управления устройствами", "контексты: Управление устройствами")
    Container("system_heating_management_service", "Сервис управления системой отопления", "контексты: Управление системой отопления")
    Container("system_lightning_management_service", "Сервис управления системой освещения", "контексты: Управление системой освещения")
    Container("gates_management_service", "Сервис управления воротами", "контексты: Управление воротами")

    Container("telemetry_service", "Сервис телеметрии", "контексты: Управление телеметрией и сбор данных")
    Container("scenario_management_service", "Сервис управления сценариями", "контексты: Управление сценариями работы и их выполнение")

    Container("heating_system_modules_api_service", "Сервис взаимодействия с модулями управления системы отопления", "")
    Container("lightning_system_modules_api_service", "Сервис взаимодействия с модулями управления системы освещения", "")
    Container("gates_modules_api_service", "Сервис взаимодействия с модулями управления воротами", "")

}

Boundary(external_house_boundary, "Дом, подключенный к системе 'Умный дом'") {
    System_Ext(heating_system, "Система управления отоплением", "API для получения данных о текущем состоянии, а также получения и установки значений температуры")
    System_Ext(lightning_system, "Система управления освещением", "API для получения данных о текущем состоянии, а также включения и выключения освещения")
    System_Ext(gates_system, "Система управления воротами", "API для получения данных о текущем состоянии, а также открытия и закрытия ворот")
}



Rel(user, api_gateway, "")
Rel(user, auth_service, "")
Rel(api_gateway, auth_service, "")
Rel(api_gateway, user_data_management_service, "")
Rel(api_gateway, device_management_service, "")
Rel(api_gateway, telemetry_service, "")
Rel(api_gateway, scenario_management_service, "")
Rel(api_gateway, system_heating_management_service, "")
Rel(api_gateway, system_lightning_management_service, "")
Rel(api_gateway, gates_management_service, "")

Rel(scenario_management_service, system_heating_management_service, "")
Rel(scenario_management_service, system_lightning_management_service, "")
Rel(scenario_management_service, gates_management_service, "")

Rel("system_heating_management_service", heating_system_modules_api_service, "Запрос текущего значения температуры, состояния системы отопления, включение/выключение системы отопления)")
Rel("system_lightning_management_service", lightning_system_modules_api_service, "Включение/выключение приборов освещения")
Rel("gates_management_service", gates_modules_api_service, "Открытие/закрытие ворот")

Rel("telemetry_service", heating_system_modules_api_service, "Запрос текущего значения температуры, состояния системы отопления (включена/выключена)")
Rel("telemetry_service", lightning_system_modules_api_service, "Запрос состояния приборов освещения (включена/выключена)")
Rel("telemetry_service", gates_modules_api_service, "Запрос положения ворот (открыты/закрыты)")

Rel(heating_system_modules_api_service, heating_system, "")
Rel(lightning_system_modules_api_service, lightning_system, "")
Rel(gates_modules_api_service, gates_system, "")


@enduml
